"""
Dataset d'entraînement pour le TextCategorizer spaCy.
Centre multisport — 13 intents, ~30 exemples chacun.
"""

INTENTS = [
    "salutation",
    "demander_heure",
    "demander_activite",
    "ask_pricing",
    "demander_lieu",
    "reserver",
    "qui",
    "cancel_booking",
    "ask_available_slots",
    "demander_mes_reservations",
    "demander_horaire_activite_inscrite",
    "demander_evenements_speciaux",
    "inconnu",
]

# Toutes les catégories à 0.0 par défaut
def cats(positive: str) -> dict:
    return {intent: 1.0 if intent == positive else 0.0 for intent in INTENTS}


TRAINING_DATA: list[tuple[str, dict]] = [

    # ── salutation ────────────────────────────────────────────────
    ("bonjour",                                         {"cats": cats("salutation")}),
    ("bonjour !",                                       {"cats": cats("salutation")}),
    ("salut",                                           {"cats": cats("salutation")}),
    ("bonsoir",                                         {"cats": cats("salutation")}),
    ("hello",                                           {"cats": cats("salutation")}),
    ("hey",                                             {"cats": cats("salutation")}),
    ("coucou",                                          {"cats": cats("salutation")}),
    ("hi",                                              {"cats": cats("salutation")}),
    ("salut comment ça va",                             {"cats": cats("salutation")}),
    ("bonjour comment allez-vous",                      {"cats": cats("salutation")}),
    ("bonsoir tout le monde",                           {"cats": cats("salutation")}),
    ("hey comment tu vas",                              {"cats": cats("salutation")}),
    ("salut, j'ai besoin d'aide",                       {"cats": cats("salutation")}),
    ("bonjour, je voudrais des informations",           {"cats": cats("salutation")}),
    ("bonsoir, pouvez-vous m'aider",                    {"cats": cats("salutation")}),
    ("bonjour je suis nouveau ici",                     {"cats": cats("salutation")}),
    ("salut, première fois que je viens",               {"cats": cats("salutation")}),
    ("hello, bonne journée",                            {"cats": cats("salutation")}),
    ("yo",                                              {"cats": cats("salutation")}),
    ("bonjour à vous",                                  {"cats": cats("salutation")}),
    ("salutations",                                     {"cats": cats("salutation")}),
    ("bonjour monsieur",                                {"cats": cats("salutation")}),
    ("bonjour madame",                                  {"cats": cats("salutation")}),

    # ── demander_heure ────────────────────────────────────────────
    ("quels sont les horaires",                             {"cats": cats("demander_heure")}),
    ("à quelle heure ouvre le centre",                      {"cats": cats("demander_heure")}),
    ("vous fermez à quelle heure",                          {"cats": cats("demander_heure")}),
    ("quel est l'horaire de la piscine",                    {"cats": cats("demander_heure")}),
    ("le planning des cours de yoga",                       {"cats": cats("demander_heure")}),
    ("quand ferme la salle de musculation",                 {"cats": cats("demander_heure")}),
    ("horaires d'ouverture",                                {"cats": cats("demander_heure")}),
    ("le centre est ouvert jusqu'à quelle heure",           {"cats": cats("demander_heure")}),
    ("vous ouvrez le dimanche",                             {"cats": cats("demander_heure")}),
    ("programme de la semaine",                             {"cats": cats("demander_heure")}),
    ("emploi du temps des cours",                           {"cats": cats("demander_heure")}),
    ("est-ce que vous êtes ouverts le samedi",              {"cats": cats("demander_heure")}),
    ("horaires du week-end",                                {"cats": cats("demander_heure")}),
    ("à partir de quelle heure puis-je venir",              {"cats": cats("demander_heure")}),
    ("quand est-ce que le centre ferme ce soir",            {"cats": cats("demander_heure")}),
    ("les horaires de la salle de fitness",                 {"cats": cats("demander_heure")}),
    ("planning hebdomadaire",                               {"cats": cats("demander_heure")}),
    ("vous êtes ouverts aujourd'hui",                       {"cats": cats("demander_heure")}),
    ("quelles sont vos heures d'ouverture",                 {"cats": cats("demander_heure")}),
    ("le tennis est disponible quand",                      {"cats": cats("demander_heure")}),
    ("horaires de fermeture ce soir",                       {"cats": cats("demander_heure")}),
    ("à quelle heure commence le premier cours",            {"cats": cats("demander_heure")}),
    ("quels sont les horaires aujourd'hui",                 {"cats": cats("demander_heure")}),
    ("heures d'ouverture de la piscine",                    {"cats": cats("demander_heure")}),
    ("vos horaires pour lundi",                             {"cats": cats("demander_heure")}),

    # ── demander_activite ─────────────────────────────────────────
    ("quelles activités proposez-vous",                     {"cats": cats("demander_activite")}),
    ("c'est quoi comme sport ici",                          {"cats": cats("demander_activite")}),
    ("liste des activités disponibles",                     {"cats": cats("demander_activite")}),
    ("qu'est-ce qu'on peut faire ici",                      {"cats": cats("demander_activite")}),
    ("vous proposez quoi comme cours",                      {"cats": cats("demander_activite")}),
    ("quels sports sont disponibles",                       {"cats": cats("demander_activite")}),
    ("info sur les cours de tennis",                        {"cats": cats("demander_activite")}),
    ("je voudrais des informations sur le yoga",            {"cats": cats("demander_activite")}),
    ("quelles disciplines proposez-vous",                   {"cats": cats("demander_activite")}),
    ("est-ce qu'il y a de la natation",                     {"cats": cats("demander_activite")}),
    ("vous faites du fitness ici",                          {"cats": cats("demander_activite")}),
    ("quels cours sont disponibles cette semaine",          {"cats": cats("demander_activite")}),
    ("il y a du badminton",                                 {"cats": cats("demander_activite")}),
    ("vous avez des cours de danse",                        {"cats": cats("demander_activite")}),
    ("est-ce qu'il y a de la zumba",                        {"cats": cats("demander_activite")}),
    ("catalogue des activités",                             {"cats": cats("demander_activite")}),
    ("quelles séances sont proposées",                      {"cats": cats("demander_activite")}),
    ("activités pour débutants",                            {"cats": cats("demander_activite")}),
    ("cours collectifs disponibles",                        {"cats": cats("demander_activite")}),
    ("vous proposez quoi comme sport aquatique",            {"cats": cats("demander_activite")}),
    ("quelles activités pour les enfants",                  {"cats": cats("demander_activite")}),
    ("y a-t-il des cours de renforcement musculaire",       {"cats": cats("demander_activite")}),
    ("quels ateliers sportifs sont proposés",               {"cats": cats("demander_activite")}),
    ("je peux pratiquer quels sports chez vous",            {"cats": cats("demander_activite")}),
    ("programme des activités du centre",                   {"cats": cats("demander_activite")}),

    # ── ask_pricing ───────────────────────────────────────────────
    ("combien ça coûte",                                    {"cats": cats("ask_pricing")}),
    ("quel est le tarif pour le fitness",                   {"cats": cats("ask_pricing")}),
    ("c'est combien l'inscription au tennis",               {"cats": cats("ask_pricing")}),
    ("quels sont les tarifs d'abonnement",                  {"cats": cats("ask_pricing")}),
    ("ça coûte combien pour un cours",                      {"cats": cats("ask_pricing")}),
    ("prix de la natation",                                 {"cats": cats("ask_pricing")}),
    ("tarif pour le yoga",                                  {"cats": cats("ask_pricing")}),
    ("combien coûte un abonnement mensuel",                 {"cats": cats("ask_pricing")}),
    ("c'est quoi les prix",                                 {"cats": cats("ask_pricing")}),
    ("grille tarifaire",                                    {"cats": cats("ask_pricing")}),
    ("tarif adhésion",                                      {"cats": cats("ask_pricing")}),
    ("forfait annuel combien",                              {"cats": cats("ask_pricing")}),
    ("abonnement famille tarif",                            {"cats": cats("ask_pricing")}),
    ("il y a un tarif étudiant",                            {"cats": cats("ask_pricing")}),
    ("réduction pour les seniors",                          {"cats": cats("ask_pricing")}),
    ("prix d'une séance unique",                            {"cats": cats("ask_pricing")}),
    ("coût de l'inscription annuelle",                      {"cats": cats("ask_pricing")}),
    ("tarif carte 10 séances",                              {"cats": cats("ask_pricing")}),
    ("combien pour un enfant",                              {"cats": cats("ask_pricing")}),
    ("package sport détente",                               {"cats": cats("ask_pricing")}),
    ("prix pour une séance de yoga",                        {"cats": cats("ask_pricing")}),
    ("combien coûte le pass semaine",                       {"cats": cats("ask_pricing")}),
    ("donnez-moi vos tarifs",                               {"cats": cats("ask_pricing")}),
    ("quel est le prix du cours de tennis",                 {"cats": cats("ask_pricing")}),
    ("tarif pour une inscription enfant",                   {"cats": cats("ask_pricing")}),

    # ── demander_lieu ─────────────────────────────────────────────
    ("où sont les vestiaires",                              {"cats": cats("demander_lieu")}),
    ("comment aller à la piscine",                          {"cats": cats("demander_lieu")}),
    ("je cherche la salle 2",                               {"cats": cats("demander_lieu")}),
    ("où se trouve l'accueil",                              {"cats": cats("demander_lieu")}),
    ("les toilettes c'est où",                              {"cats": cats("demander_lieu")}),
    ("où est la salle de fitness",                          {"cats": cats("demander_lieu")}),
    ("comment accéder aux courts de tennis",                {"cats": cats("demander_lieu")}),
    ("où sont les casiers",                                 {"cats": cats("demander_lieu")}),
    ("je cherche la réception",                             {"cats": cats("demander_lieu")}),
    ("direction salle A",                                   {"cats": cats("demander_lieu")}),
    ("où est le secrétariat",                               {"cats": cats("demander_lieu")}),
    ("comment trouver la salle de yoga",                    {"cats": cats("demander_lieu")}),
    ("je suis perdu, où est le bassin",                     {"cats": cats("demander_lieu")}),
    ("emplacement du terrain de basket",                    {"cats": cats("demander_lieu")}),
    ("où puis-je garer mon vélo",                           {"cats": cats("demander_lieu")}),
    ("les douches sont où",                                 {"cats": cats("demander_lieu")}),
    ("où se trouve la salle B",                             {"cats": cats("demander_lieu")}),
    ("localisation du bureau d'information",               {"cats": cats("demander_lieu")}),
    ("chemin vers la piscine",                              {"cats": cats("demander_lieu")}),
    ("où est l'entrée principale",                          {"cats": cats("demander_lieu")}),
    ("où puis-je trouver la salle de spinning",             {"cats": cats("demander_lieu")}),
    ("indique-moi où est le vestiaire hommes",              {"cats": cats("demander_lieu")}),
    ("où se trouve la sortie",                              {"cats": cats("demander_lieu")}),
    ("comment aller vers la salle de danse",                {"cats": cats("demander_lieu")}),
    ("où est la zone d'attente",                            {"cats": cats("demander_lieu")}),

    # ── reserver ──────────────────────────────────────────────────
    ("je voudrais réserver un cours de fitness",            {"cats": cats("reserver")}),
    ("inscription pour la natation",                        {"cats": cats("reserver")}),
    ("prendre un cours de tennis demain",                   {"cats": cats("reserver")}),
    ("réservation terrain de badminton",                    {"cats": cats("reserver")}),
    ("je veux m'inscrire au yoga",                          {"cats": cats("reserver")}),
    ("réserver une place pour le cours de zumba",           {"cats": cats("reserver")}),
    ("je souhaite réserver la salle A",                     {"cats": cats("reserver")}),
    ("book un créneau de musculation",                      {"cats": cats("reserver")}),
    ("je voudrais prendre un cours de pilates",             {"cats": cats("reserver")}),
    ("réserver un court de squash",                         {"cats": cats("reserver")}),
    ("s'inscrire à la séance de cardio",                    {"cats": cats("reserver")}),
    ("je veux réserver pour lundi matin",                   {"cats": cats("reserver")}),
    ("inscrire mon enfant au cours de natation",            {"cats": cats("reserver")}),
    ("réserver le terrain de foot",                         {"cats": cats("reserver")}),
    ("je veux une place pour le cours de stretching",       {"cats": cats("reserver")}),
    ("prendre rendez-vous pour un bilan sportif",           {"cats": cats("reserver")}),
    ("réserver un créneau aquagym",                         {"cats": cats("reserver")}),
    ("je souhaite m'inscrire à la zumba de jeudi",          {"cats": cats("reserver")}),
    ("réserver salle de sport demain",                      {"cats": cats("reserver")}),
    ("inscrire pour la prochaine séance",                   {"cats": cats("reserver")}),
    ("je veux réserver deux places pour le yoga",           {"cats": cats("reserver")}),
    ("peux-tu me réserver un créneau ce soir",              {"cats": cats("reserver")}),
    ("merci de réserver un terrain de tennis",              {"cats": cats("reserver")}),
    ("je souhaite réserver une séance de natation",         {"cats": cats("reserver")}),
    ("réservez-moi une place pour demain matin",            {"cats": cats("reserver")}),

    # ── qui ───────────────────────────────────────────────────────
    ("qui es-tu",                                           {"cats": cats("qui")}),
    ("c'est quoi ton nom",                                  {"cats": cats("qui")}),
    ("présente-toi",                                        {"cats": cats("qui")}),
    ("qui t'a créé",                                        {"cats": cats("qui")}),
    ("tu es un robot",                                      {"cats": cats("qui")}),
    ("comment tu t'appelles",                               {"cats": cats("qui")}),
    ("c'est qui toi",                                       {"cats": cats("qui")}),
    ("tu es quoi exactement",                               {"cats": cats("qui")}),
    ("qui êtes-vous",                                       {"cats": cats("qui")}),
    ("vous êtes un humain ou un robot",                     {"cats": cats("qui")}),
    ("t'es une IA",                                         {"cats": cats("qui")}),
    ("qui a développé ce robot",                            {"cats": cats("qui")}),
    ("comment vous appelez-vous",                           {"cats": cats("qui")}),
    ("ton identité",                                        {"cats": cats("qui")}),
    ("présente-toi s'il te plaît",                          {"cats": cats("qui")}),
    ("d'où tu viens",                                       {"cats": cats("qui")}),
    ("tu es une intelligence artificielle",                 {"cats": cats("qui")}),
    ("quel est ton rôle ici",                               {"cats": cats("qui")}),
    ("tu peux te présenter rapidement",                     {"cats": cats("qui")}),
    ("qui parle avec moi",                                  {"cats": cats("qui")}),
    ("à qui ai-je affaire",                                 {"cats": cats("qui")}),
    ("tu es l'assistant du centre",                         {"cats": cats("qui")}),
    ("tu peux me dire qui tu es",                           {"cats": cats("qui")}),

    # ── cancel_booking ────────────────────────────────────────────
    ("je voudrais annuler ma réservation",                  {"cats": cats("cancel_booking")}),
    ("annule ma réservation pour la salle A",               {"cats": cats("cancel_booking")}),
    ("je souhaite supprimer ma réservation",                {"cats": cats("cancel_booking")}),
    ("résilier mon cours de natation",                      {"cats": cats("cancel_booking")}),
    ("annulez ma réservation",                              {"cats": cats("cancel_booking")}),
    ("je ne peux plus venir, annulez mon cours",            {"cats": cats("cancel_booking")}),
    ("déprogrammer ma séance de yoga",                      {"cats": cats("cancel_booking")}),
    ("supprimer mon inscription au fitness",                {"cats": cats("cancel_booking")}),
    ("je veux me désister du cours de lundi",               {"cats": cats("cancel_booking")}),
    ("annulation de ma réservation de tennis",              {"cats": cats("cancel_booking")}),
    ("retirer ma place au cours de pilates",                {"cats": cats("cancel_booking")}),
    ("je ne viendrai pas, merci d'annuler",                 {"cats": cats("cancel_booking")}),
    ("cancel ma résa",                                      {"cats": cats("cancel_booking")}),
    ("annuler le cours de demain",                          {"cats": cats("cancel_booking")}),
    ("je veux abandonner ma réservation",                   {"cats": cats("cancel_booking")}),
    ("supprime ma séance de cardio",                        {"cats": cats("cancel_booking")}),
    ("je dois annuler mon yoga",                            {"cats": cats("cancel_booking")}),
    ("je ne viens plus ce soir, annule",                    {"cats": cats("cancel_booking")}),
    ("désistement pour la zumba de jeudi",                  {"cats": cats("cancel_booking")}),
    ("annuler inscription badminton",                       {"cats": cats("cancel_booking")}),
    ("merci d'annuler ma réservation de ce matin",          {"cats": cats("cancel_booking")}),
    ("je souhaite annuler mon créneau de musculation",      {"cats": cats("cancel_booking")}),
    ("veuillez annuler mon cours de demain",                {"cats": cats("cancel_booking")}),
    ("je veux retirer ma réservation",                      {"cats": cats("cancel_booking")}),
    ("annule ma place pour la natation",                    {"cats": cats("cancel_booking")}),

    # ── ask_available_slots ───────────────────────────────────────
    ("quels créneaux sont disponibles",                     {"cats": cats("ask_available_slots")}),
    ("quand est-ce que je peux venir",                      {"cats": cats("ask_available_slots")}),
    ("il y a des places pour le yoga",                      {"cats": cats("ask_available_slots")}),
    ("créneaux disponibles pour la natation",               {"cats": cats("ask_available_slots")}),
    ("quelles heures sont libres demain",                   {"cats": cats("ask_available_slots")}),
    ("est-ce qu'il reste des places pour le fitness",       {"cats": cats("ask_available_slots")}),
    ("disponibilités pour le tennis ce week-end",           {"cats": cats("ask_available_slots")}),
    ("quels horaires sont encore ouverts",                  {"cats": cats("ask_available_slots")}),
    ("il y a de la place pour ce soir",                     {"cats": cats("ask_available_slots")}),
    ("montrer les disponibilités",                          {"cats": cats("ask_available_slots")}),
    ("les créneaux libres pour le badminton",               {"cats": cats("ask_available_slots")}),
    ("quand puis-je réserver un cours de pilates",          {"cats": cats("ask_available_slots")}),
    ("afficher les horaires disponibles",                   {"cats": cats("ask_available_slots")}),
    ("slots disponibles pour la musculation",               {"cats": cats("ask_available_slots")}),
    ("est-ce qu'il y a de la place lundi",                  {"cats": cats("ask_available_slots")}),
    ("disponibilité salle de sport jeudi matin",            {"cats": cats("ask_available_slots")}),
    ("vous avez encore de la place pour zumba",             {"cats": cats("ask_available_slots")}),
    ("horaires libres cette semaine",                       {"cats": cats("ask_available_slots")}),
    ("créneaux ouverts pour le squash",                     {"cats": cats("ask_available_slots")}),
    ("quand peut-on encore s'inscrire",                     {"cats": cats("ask_available_slots")}),
    ("reste-t-il des créneaux en soirée",                   {"cats": cats("ask_available_slots")}),
    ("quelles disponibilités pour samedi matin",            {"cats": cats("ask_available_slots")}),
    ("quels créneaux restent pour aujourd'hui",              {"cats": cats("ask_available_slots")}),
    ("il reste de la place en fin d'après-midi",            {"cats": cats("ask_available_slots")}),
    ("dispo pour un cours de yoga mardi",                   {"cats": cats("ask_available_slots")}),

    # ── demander_mes_reservations ─────────────────────────────────
    ("mes réservations",                                    {"cats": cats("demander_mes_reservations")}),
    ("voir mes réservations",                               {"cats": cats("demander_mes_reservations")}),
    ("afficher mes réservations",                           {"cats": cats("demander_mes_reservations")}),
    ("j'ai réservé quoi",                                   {"cats": cats("demander_mes_reservations")}),
    ("liste de mes réservations",                           {"cats": cats("demander_mes_reservations")}),
    ("vérifier mes réservations",                           {"cats": cats("demander_mes_reservations")}),
    ("quels cours ai-je réservé",                           {"cats": cats("demander_mes_reservations")}),
    ("mes prochains cours",                                 {"cats": cats("demander_mes_reservations")}),
    ("récapitulatif de mes réservations",                   {"cats": cats("demander_mes_reservations")}),
    ("j'ai quels cours cette semaine",                      {"cats": cats("demander_mes_reservations")}),
    ("résumé de mes activités réservées",                   {"cats": cats("demander_mes_reservations")}),
    ("mes inscriptions en cours",                           {"cats": cats("demander_mes_reservations")}),
    ("affiche mes bookings",                                {"cats": cats("demander_mes_reservations")}),
    ("je veux voir mes cours réservés",                     {"cats": cats("demander_mes_reservations")}),
    ("confirmer mes réservations",                          {"cats": cats("demander_mes_reservations")}),
    ("détails de mes réservations",                         {"cats": cats("demander_mes_reservations")}),
    ("quand est mon prochain cours",                        {"cats": cats("demander_mes_reservations")}),
    ("mes séances à venir",                                 {"cats": cats("demander_mes_reservations")}),
    ("voir mes activités planifiées",                       {"cats": cats("demander_mes_reservations")}),
    ("quelles sont mes réservations pour cette semaine",    {"cats": cats("demander_mes_reservations")}),
    ("montre-moi toutes mes réservations",                  {"cats": cats("demander_mes_reservations")}),
    ("je veux consulter mes créneaux réservés",             {"cats": cats("demander_mes_reservations")}),
    ("peux-tu lister mes réservations",                     {"cats": cats("demander_mes_reservations")}),
    ("je veux voir mes séances de la semaine",              {"cats": cats("demander_mes_reservations")}),
    ("mes réservations actives",                            {"cats": cats("demander_mes_reservations")}),

    # ── demander_horaire_activite_inscrite ──────────────────────
    ("à quelle heure est mon cours de yoga",                {"cats": cats("demander_horaire_activite_inscrite")}),
    ("c'est quand ma séance de natation",                   {"cats": cats("demander_horaire_activite_inscrite")}),
    ("quel est l'horaire de mon cours réservé",             {"cats": cats("demander_horaire_activite_inscrite")}),
    ("je suis inscrit au pilates, c'est à quelle heure",    {"cats": cats("demander_horaire_activite_inscrite")}),
    ("à quelle heure commence mon activité",                {"cats": cats("demander_horaire_activite_inscrite")}),
    ("quand est mon prochain cours réservé",                {"cats": cats("demander_horaire_activite_inscrite")}),
    ("horaire de mon inscription badminton",                {"cats": cats("demander_horaire_activite_inscrite")}),
    ("mon cours de zumba est prévu à quelle heure",         {"cats": cats("demander_horaire_activite_inscrite")}),

    # ── demander_evenements_speciaux ─────────────────────────────
    ("y a-t-il un tournoi en cours",                        {"cats": cats("demander_evenements_speciaux")}),
    ("quels événements spéciaux sont prévus",               {"cats": cats("demander_evenements_speciaux")}),
    ("je veux des infos sur le prochain tournoi",           {"cats": cats("demander_evenements_speciaux")}),
    ("quel est l'événement à venir",                        {"cats": cats("demander_evenements_speciaux")}),
    ("il y a une compétition cette semaine",                {"cats": cats("demander_evenements_speciaux")}),
    ("programme des événements spéciaux",                   {"cats": cats("demander_evenements_speciaux")}),
    ("des tournois bientôt au centre",                      {"cats": cats("demander_evenements_speciaux")}),
    ("infos sur les événements sportifs à venir",           {"cats": cats("demander_evenements_speciaux")}),

    # ── inconnu ───────────────────────────────────────────────────
    ("la météo aujourd'hui",                                {"cats": cats("inconnu")}),
    ("tu peux me faire une pizza",                          {"cats": cats("inconnu")}),
    ("quel est le sens de la vie",                          {"cats": cats("inconnu")}),
    ("j'aime le sport",                                     {"cats": cats("inconnu")}),
    ("merci beaucoup",                                      {"cats": cats("inconnu")}),
    ("ok d'accord",                                         {"cats": cats("inconnu")}),
    ("c'est super",                                         {"cats": cats("inconnu")}),
    ("je ne sais pas",                                      {"cats": cats("inconnu")}),
    ("au revoir",                                           {"cats": cats("inconnu")}),
    ("bonne journée",                                       {"cats": cats("inconnu")}),
    ("pouvez-vous parler moins vite",                       {"cats": cats("inconnu")}),
    ("parle plus fort",                                     {"cats": cats("inconnu")}),
    ("je n'ai pas compris",                                 {"cats": cats("inconnu")}),
    ("répète s'il te plaît",                                {"cats": cats("inconnu")}),
    ("je viens de Paris",                                   {"cats": cats("inconnu")}),
    ("quelle est la capitale de la France",                 {"cats": cats("inconnu")}),
    ("raconte-moi une blague",                              {"cats": cats("inconnu")}),
    ("tu connais Netflix",                                  {"cats": cats("inconnu")}),
    ("fais-moi un résumé d'un film",                        {"cats": cats("inconnu")}),
    ("quelle heure est-il à Tokyo",                         {"cats": cats("inconnu")}),
    ("raconte-moi une histoire",                            {"cats": cats("inconnu")}),
    ("quel temps fait-il demain",                           {"cats": cats("inconnu")}),
    ("écris un poème",                                      {"cats": cats("inconnu")}),
]